// <auto-generated />
namespace CakeDistribution.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DessertMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DessertMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202105271541116_DessertMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
